// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'special_chars_test.dart' as special_chars_test;
import 'table_alignment_test.dart' as table_alignment_test;
import 'table_border_test.dart' as table_border_test;

void main() {
  table_border_test.main();
  table_alignment_test.main();
  special_chars_test.main();
}
