// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'int_count_test.dart' as int_count_test;
import 'model_test.dart' as model_test;
import 'span_test.dart' as span_test;
import 'special_chars_test.dart' as special_chars_test;
import 'table_alignment_test.dart' as table_alignment_test;
import 'table_border_test.dart' as table_border_test;
import 'text_test.dart' as text_test;

void main() {
  table_border_test.main();
  table_alignment_test.main();
  span_test.main();
  model_test.main();
  int_count_test.main();
  special_chars_test.main();
  text_test.main();
}
