name: barbecue
description: Render text tables for your command line applications. Use padding, spans, custom borders, ANSI colors and more!
version: 0.5.0
homepage: https://github.com/knaeckeKami/barbecue

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  characters: ^1.1.0
  collection: ^1.15.0
  string_validator: ^1.0.0
  meta: ^1.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
  coverage: ^1.7.2
