name: barbecue
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/knaeckeKami/barbecue

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  characters: ^1.0.0
  meta: ^1.2.3
  collection: ^1.14.13

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.4
  test_coverage: ^0.4.3
