name: barbecue
description: Render text tables for your command line applications. Use padding, spans, custom borders, ANSI colors and more!
version: 0.4.0
homepage: https://github.com/knaeckeKami/barbecue

environment:

  sdk: '>=2.12.0 <3.0.0'

dependencies:
  characters: ^1.1.0
  collection: ^1.15.0
  string_validator: ^0.3.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.12
