name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dart-lang/setup-dart@v1
    - name: Install dependencies
      run: dart pub get

    - name: Check format
      run: dart format --set-exit-if-changed .
    
    - name: Analyze
      run: dart analyze

    - name: Run tests
      run: pub run test

    - name: Coverage
      run: dart pub glocal activate coverage && dart pub global run coverage:test_with_coverage

    - name: Upload coverage to codecov
      run: curl -s https://codecov.io/bash | bash
